from dotenv import load_dotenv
from google import genai
from datetime import datetime
import os, json

load_dotenv()
client = genai.Client(api_key=os.getenv("GEMINI_API_KEY")) # get the API key

# function to get response from AI model, based on the prompt argument parsed
def get_ai_output(prompt_to_ai):
    response = client.models.generate_content(
        model="gemini-3.8-flash",
        contents=prompt_to_ai
    )
    return response


# log any API failiures in a log file
def log_error(error):
    with open("error.log", "a") as logfile:
        logfile.write(
            f"{datetime.now()} - API Error: {error}\n"
        )
        
        
# check if the API is available to use or down due to high demand etc.
def check_api_status():
    try:
        get_ai_output("Reply with the word OK.")
        return True
    except Exception as e:
        return e


# check if message is a scam or not
def analyse_message():
    # the prompt to send to the AI model
    # prompt = f"""
    # You are an AI Scam Risk Investigation Assistant.
    # Analyse the following message and determine if it is potentially a scam.
    
    # Message:
    # {message_content}
    
    # Source:
    # {source_content}
    
    # Return a JSON object with the following fields:
    # - time_stamp
    # - scam_probability
    # - risk_level
    # - scam_type
    # - indicators
    # - explanation
    # - recommendation
    
    # Rules:
    # - Return the timestamp value as an empty string. Do not modify the timestamp value.
    # - scam_probability must be an integer from 0 to 100.
    # - risk_level, a string value, must be "HIGH" if scam_probability >= 80 and "MEDIUM" if scam_probability >= 50. Else, must be "LOW".
    # - scam_type, a string value, must be one of the following:
    #     - Banking Scam
    #     - Job Scam
    #     - Parcel Delivery Scam
    #     - Prize Money Scam
    #     - Government Scam
    #     - Other Scam
    # - indicators must be a list of detected scam indicators.
    # - explanation, a string value, must explain why the message may be suspicious.
    # - recommendation, a string value, must provide advice to the user on follow up actions based on the severity and type of scam message.
    
    # Output restrictions:
    # - Return only a JSON object in this format:
    # {{
    #     # TODO: Insert JSON schema here.
    # }}
    # - Do not include markdown, code blocks, or any text outside the JSON object.
    # """
    
    prompt = "Return the phrase: My prompt for the AI." # * For simple testing purposes
    
    # Check API staus before sending prompt to AI model
    api_status = check_api_status()
    
    if api_status is True:
        response = get_ai_output(prompt) # get the response object from the AI model
        
        try:
            ai_output = json.loads(response.text) # convert the raw text generated by AI model into a JSON object)
        except json.JSONDecodeError:
            return None
        
    else:
        # log error and use fallback bot function
        log_error(api_status) 
        ai_output = None # * Teporarily put as None
        # TODO: Call fallback funtion (i.e. our own bot)
    
    # * Need to get the ai_output object first before assigning date and time.
    # ai_output["timestamp"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S") # format timestamp as YYYY-MM-DD HH:MM:SS
    # print(ai_output) # to check ai_output value
    return ai_output

analyse_message()