from dotenv import load_dotenv
from google import genai
import os

load_dotenv()
client = genai.Client(api_key=os.getenv("GEMINI_API_KEY")) # get the API key

def analyse_message(message_content, source_content):
    # the prompt to send to the AI model
    prompt = f"""
    You are an AI Scam Risk Investigation Assistant.
    Analyse the following message and determine if it is potentially a scam.
    
    Message:
    {message_content}
    
    Source:
    {source_content}
    
    Return a JSON object with the following fields:
    - scam_probability
    - risk_level
    - scam_type
    - indicators
    - explanation
    - recommendation
    
    Rules:
    - scam_probability must be an integer from 0 to 100.
    - risk_level, a string value, must be "High" if scam_probability >= 80 and "Medium" if scam_probability >= 50. Else, must be "Low".
    - scam_type, a string value, must be one of the following:
        - Banking Scam
        - Job Scam
        - Parcel Delivery Scam
        - Prize Money Scam
        - Government Scam
        - Other Scam
    - indicators must be a list of detected scam indicators.
    - explanation, a string value, must explain why the message may be suspicious.
    - recommendation, a string value, must provide advice to the user on follow up actions based on the severity and type of scam message.
    
    Output restrictions:
    - Return only a JSON object in this format:
    {{
        # TODO: Insert JSON schema here.
    }}
    - Do not include markdown, code blocks, or any text outside the JSON object.
    """
    
    response = client.models.generate_content(
        model="gemini-3.6-flash",
        contents=prompt
    )
    
    return response.text # return the raw text generated by AI model (i.e. the JSON object)