from dotenv import load_dotenv
from google import genai
from datetime import datetime
import os, json, logging

load_dotenv()
logging.getLogger().setLevel(logging.ERROR) # hide warning messages from the Gemini SDK which uses Python's logging module
client = genai.Client(api_key=os.getenv("GEMINI_API_KEY")) # get the API key

# class FakeResponse:
#     text = "this is not JSON"
    
# class ValidResponse:
#     text = """
#     some text before the json object
    
#     {
#         "phone_number": "+6591234567",
#         "message_content": "URGENT: Your bank account has been suspended. Click the link to verify your identity.",
#         "scam_probability": 91,
#         "risk_level": "HIGH",
#         "scam_type": "Banking Scam",
#         "indicators": [
#             "Urgency Language",
#             "Account Suspension Threat",
#             "Request for Verification"
#         ],
#         "explanation": "The message creates urgency and attempts to impersonate a bank to trick the recipient into revealing information.",
#         "recommendation": "Do not click any links. Contact the bank using official contact channels."
#     }
    
#     some text after the json object
#     """
    
    
# function to get response from AI model, based on the prompt argument parsed
def get_ai_output(prompt_to_ai):
    response = client.models.generate_content(
        model="gemini-3.6-flash",
        contents=prompt_to_ai
    )
    return response

# grab only the JSON object in the AI output if there are strings before and after it
def extract_json_object(text):
    start = text.find("{")
    end = text.rfind("}")
    
    if start != -1 and end != -1: 
        json_string = text[start:end + 1]       
        return json.loads(json_string) # return the JSON string as a JSON object


# log any API failiures in a log file
def log_error(error):
    with open("error.log", "a") as logfile:
        logfile.write(
            f"{datetime.now()} - Error: {error}\n"
        )
        
        
# check if the API is available to use or down due to high demand etc.
def check_api_status():
    try:
        get_ai_output("Reply with the phrase: API IS OK.")
        return True
    except Exception as e:
        return e


# check if message is a scam or not
def analyse_message(message_content, source_content):
    # the prompt to send to the AI model
    prompt = f"""
    You are an AI Scam Risk Investigation Assistant.
    Analyse the following message and determine if it is potentially a scam.
    
    Message:
    {message_content}
    
    Source:
    {source_content}
    
    Return a JSON object with the following fields:
    - scam_probability
    - risk_level
    - scam_type
    - indicators
    - explanation
    - recommendation
    
    Rules:
    - scam_probability must be an integer from 0 to 100.
    - risk_level, a string value, must be "HIGH" if scam_probability >= 80 and "MEDIUM" if scam_probability >= 50. Else, must be "LOW".
    - scam_type, a string value, must be one of the following:
        - Impersonation Scam
        - Banking Scam
        - Fake Subscription Scam
        - Fake Website Scam
        - Job Scam
        - Parcel Delivery Scam
        - Unexpected Prize Money Scam
        - Government Scam
        - Other Scam
    - indicators must be a list of detected scam indicators from the analysed message.
    - explanation, a string value, must explain why the message may be suspicious.
    - recommendation, a string value, must provide advice to the user on follow up actions based on the severity and type of scam message.
    
    Output restrictions:
    - Return only a JSON object in this format:
    {{
        "phone_number": "",
        "message_content": "",
        "scam_probability": 0, 
        "risk_level": "",
        "scam_type": "",
        "indicators": [],
        "explanation": "",
        "recommendation": ""    
    }}
    - Do not include markdown, code blocks, or any text outside the JSON object.
    """
    
    # * message_id field will be added when writing to database.
    
    # prompt = "Return the phrase: My prompt for the AI." # * For simple testing purposes
    
    # Check API staus before sending prompt to AI model
    api_status = check_api_status()
    
    if api_status is True:
        print(f"Message analysis in progress using Google Gemini 3.6 Flash. This may take a few seconds... \n")
        print(api_status)
        response = get_ai_output(prompt) # get the response object from the AI model
        # response = ValidResponse()
        try:
            ai_output = json.loads(response.text) # convert the raw text generated by AI model into a JSON object
            # ai_output["timestamp"] = (datetime.now()).strftime("%Y-%m-%d %H:%M:%S") # add timestamp field to track when the message analysis is done.
        except json.JSONDecodeError as error:
            print(f"The JSONDecode Error is : {error}")
            ai_output = extract_json_object(response.text)
    else:
        # print error message, log error and use fallback bot function
        print(api_status.message) # api_status is a ServerError object when api is unavailable
        log_error(api_status) 
        ai_output = None # * Teporarily put as None
        # TODO: go back to IO manager to prompt user if they still want to use our bot or not (quit)
        # TODO: Call fallback funtion (i.e. prompt user if they want to use our own bot)
        # * If don't want to use bot, go back to main menu
    
    # * Need to get the ai_output object first before assigning date and time.
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S") # format timestamp as YYYY-MM-DD HH:MM:SS
    ai_output = {"timestamp": timestamp, **ai_output} # insert timestamp at the front of the JSON object
    print(ai_output) # to check the final value of ai_output
    return ai_output

test_message_content = """
URGENT: Your DBS account has been suspended due to suspicious activity.

To avoid permanent suspension, verify your account immediately at:

https://dbs-secure-verify.com

Failure to verify within 24 hours may result in account restrictions.

DBS Security Team
"""

test_message_source = "+6591234567"


analyse_message(test_message_content, test_message_source)